### ISSUE TITLE
postmaster pwd too short, but domain is created anyway

### ISSUE THREAD

**Issue by sagredo-dev** [brunonymous/vpopmail#1]
If I try to create a domain and enter a pwd with less than 12 characters the postmaster user is not added, but the domain folder is created anyway on disk.
I think that it would be great if the error message will suggest the minimum lenght allowed, just to avoid try and errors to those who didn't looked at the code.

Thanks for your work!

**Comment by PatriceDuh** [comment]
Thanks, we fixed it by removing the domain if postmaster creation fails.

Tell us if this solution works for you.
