### ISSUE TITLE
Future of your vpopmail

### ISSUE THREAD

**Issue by sagredo-dev** [brunonymous/vpopmail#6]
Hi, great job there!
I'm planning to pull my latest modifications of vpopmail that you can find at notes.sagredo.eu. Do you have plans to mantain this vpopmail distribution in the long term?  Can the actual situation be considered stable? If yes, is it possible to release a tag, so that we can download from that point?

Thanks for any answer

**Comment by PatriceDuh** [comment]
Yes, we will continue to maintain this version of vpopmail, and we are looking to release it.
But actually, LDAP support is broken and we need to test PostgreSQL and Oracle.
