### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by sagredo-dev** [brunonymous/vpopmail#9]
Hi, just wanted to inform that I'm publishing a new release in my fork to let my users download my vpopmail package. If you prefer I will link directly to your future release when ready.

**Comment by brunonymous** [comment]
Hi Roberto, I'm not at all used to using GitHub to release a new version. I suppose the new version will be 5.4.34? What are the possibilities? Would you prefer to have access to my repository to release version 5.4.34? Don't forget to update the ChangeLog and config.h files with the new version number.

**Comment by sagredo-dev** [comment]
Hi Bruno, for me it is a bigger step, so I would name it 5.6, avoiding 5.5 as vpopmail-5.5 already existed as a development version, but it's not that important... 5.4.34 would be fine as well.
I can help in doing that but I think that is very very easy... I learned myself a couple of days ago :-) Just click on the "create a new release" on the right, then create a tag and finally create the release inside that tag.
Release name/versions are a little tricky at the beginning: when  you create a release, say v5.4.33, when the user download and extract the v5.433.tar.gz file (s)he has a vpopmail-5.4.33 folder, so the project name is inserted.

I'm happy that a new release will see the light soon. I'll direct my users to your releases and continue to post PR here.
